In [1]:
import pandas as pd

In [2]:
df_csv = pd.read_csv('../data/raw/December_2014_Permits.csv')

/Users/graceharmon/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (1,12) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [3]:
df = df_csv

In [4]:
df.head()

,Assessor Book,Assessor Page,Assessor Parcel,Tract,Block,Lot,Reference # (Old Permit #),PCIS Permit #,Permit Type,Permit Sub-Type,...,Applicant Last Name,Applicant Business Name,Applicant Address 1,Applicant Address 2,Applicant Address 3,Zone,Occupancy,Floor Area-L.A. Building Code Definition,Census Tract,Latitude/Longitude
0,5017.0,25.0,015,MILHOUSE VERMONT AVENUE TRACT,NaN,3,NaN,20041-10000-19010,Electrical,Commercial,...,MENDOZA,NaN,NaN,NaN,NaN,C2-1VL-CPIO,NaN,0.0,2323.00,"(33.99616, -118.29167)"
1,5478.0,17.0,040,TR 2596,NaN,99,NaN,19041-10000-34160,Electrical,1 or 2 Family Dwelling,...,LEUNG,OWNER-BUILDER,NaN,NaN,NaN,R1-1,NaN,0.0,1835.10,"(34.11679, -118.20276)"
2,4422.0,6.0,007,TR 9300,80,3,20WL05483,16030-30001-00598,Bldg-Alter/Repair,1 or 2 Family Dwelling,...,TORRES,NaN,NaN,NaN,NaN,R1-1,NaN,NaN,2625.01,"(34.05319, -118.52005)"
3,4260.0,17.0,024,TR 8369,NaN,60,NaN,20043-10000-04664,Fire Sprinkler,Commercial,...,Kivity,NaN,7651 Densmore avenue,NaN,Van Nuys,M2-1,NaN,0.0,2677.00,"(34.03666, -118.44346)"
4,5561.0,6.0,041,P M 3813,NaN,C,20WL06519,16010-30003-05895,Bldg-Addition,1 or 2 Family Dwelling,...,WHITEHEAD,NaN,NaN,NaN,NaN,RE15-1-H,NaN,576.0,1943.00,"(34.10161, -118.38808)"

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1164250 entries, 0 to 1164249
Data columns (total 52 columns):
 #   Column                                    Non-Null Count    Dtype
---  ------                                    --------------    -----
 0   Assessor Book                             1163365 non-null  float64
 1   Assessor Page                             1163365 non-null  object
 2   Assessor Parcel                           1163365 non-null  object
 3   Tract                                     1159780 non-null  object
 4   Block                                     223014 non-null   object
 5   Lot                                       1156720 non-null  object
 6   Reference # (Old Permit #)                505301 non-null   object
 7   PCIS Permit #                             1164250 non-null  object
 8   Permit Type                               1164250 non-null  object
 9   Permit Sub-Type                           1164250 non-null  object
 10  Permit Category                           1164250 non-null  object
 11  Project Number                            9236 non-null     float64
 12  Event Code                                3 non-null        object
 13  Initiating Office                         1164250 non-null  object
 14  Issue Date                                1164250 non-null  object
 15  Address Start                             1164240 non-null  float64
 16  Address Fraction Start                    16675 non-null    object
 17  Address End                               1164236 non-null  float64
 18  Address Fraction End                      29871 non-null    object
 19  Street Direction                          1153361 non-null  object
 20  Street Name                               1164244 non-null  object
 21  Street Suffix                             1140790 non-null  object
 22  Suffix Direction                          6931 non-null     object
 23  Unit Range Start                          222395 non-null   object
 24  Unit Range End                            26560 non-null    object
 25  Zip Code                                  1164179 non-null  float64
 26  Work Description                          527826 non-null   object
 27  Valuation                                 442810 non-null   float64
 28  Floor Area-L.A. Zoning Code Definition    99646 non-null    float64
 29  # of Residential Dwelling Units           54677 non-null    float64
 30  # of Stories                              100366 non-null   float64
 31  Contractor's Business Name                1163762 non-null  object
 32  Contractor Address                        1005022 non-null  object
 33  Contractor City                           1001381 non-null  object
 34  Contractor State                          1001286 non-null  object
 35  License Type                              1008914 non-null  object
 36  License #                                 1164222 non-null  float64
 37  Principal First Name                      1015067 non-null  object
 38  Principal Middle Name                     705416 non-null   object
 39  Principal Last Name                       1017244 non-null  object
 40  License Expiration Date                   1051210 non-null  object
 41  Applicant First Name                      1016401 non-null  object
 42  Applicant Last Name                       880150 non-null   object
 43  Applicant Business Name                   92581 non-null    object
 44  Applicant Address 1                       669479 non-null   object
 45  Applicant Address 2                       194063 non-null   object
 46  Applicant Address 3                       661260 non-null   object
 47  Zone                                      1161433 non-null  object
 48  Occupancy                                 17318 non-null    object
 49  Floor Area-L.A. Building Code Definition  914193 non-null   float64
 50  Census Tract                              1163510 non-null  float64
 51  Latitude/Longitude                        1096344 non-null  object
dtypes: float64(12), object(40)
memory usage: 461.9+ MB

In [6]:
df.columns = df.columns.str.upper()

In [9]:
df.columns = df.columns.str.replace(' ', '_')

In [10]:
df.columns

Index(['ASSESSOR_BOOK', 'ASSESSOR_PAGE', 'ASSESSOR_PARCEL', 'TRACT', 'BLOCK',
       'LOT', 'REFERENCE_#_(OLD_PERMIT_#)', 'PCIS_PERMIT_#', 'PERMIT_TYPE',
       'PERMIT_SUB-TYPE', 'PERMIT_CATEGORY', 'PROJECT_NUMBER', 'EVENT_CODE',
       'INITIATING_OFFICE', 'ISSUE_DATE', 'ADDRESS_START',
       'ADDRESS_FRACTION_START', 'ADDRESS_END', 'ADDRESS_FRACTION_END',
       'STREET_DIRECTION', 'STREET_NAME', 'STREET_SUFFIX', 'SUFFIX_DIRECTION',
       'UNIT_RANGE_START', 'UNIT_RANGE_END', 'ZIP_CODE', 'WORK_DESCRIPTION',
       'VALUATION', 'FLOOR_AREA-L.A._ZONING_CODE_DEFINITION',
       '#_OF_RESIDENTIAL_DWELLING_UNITS', '#_OF_STORIES',
       'CONTRACTOR'S_BUSINESS_NAME', 'CONTRACTOR_ADDRESS', 'CONTRACTOR_CITY',
       'CONTRACTOR_STATE', 'LICENSE_TYPE', 'LICENSE_#', 'PRINCIPAL_FIRST_NAME',
       'PRINCIPAL_MIDDLE_NAME', 'PRINCIPAL_LAST_NAME',
       'LICENSE_EXPIRATION_DATE', 'APPLICANT_FIRST_NAME',
       'APPLICANT_LAST_NAME', 'APPLICANT_BUSINESS_NAME', 'APPLICANT_ADDRESS_1',
       'APPLICANT_ADDRESS_2', 'APPLICANT_ADDRESS_3', 'ZONE', 'OCCUPANCY',
       'FLOOR_AREA-L.A._BUILDING_CODE_DEFINITION', 'CENSUS_TRACT',
       'LATITUDE/LONGITUDE'],
      dtype='object')

In [11]:
df.sort_values('PERMIT_TYPE' , ascending=False).head()

,ASSESSOR_BOOK,ASSESSOR_PAGE,ASSESSOR_PARCEL,TRACT,BLOCK,LOT,REFERENCE_#_(OLD_PERMIT_#),PCIS_PERMIT_#,PERMIT_TYPE,PERMIT_SUB-TYPE,...,APPLICANT_LAST_NAME,APPLICANT_BUSINESS_NAME,APPLICANT_ADDRESS_1,APPLICANT_ADDRESS_2,APPLICANT_ADDRESS_3,ZONE,OCCUPANCY,FLOOR_AREA-L.A._BUILDING_CODE_DEFINITION,CENSUS_TRACT,LATITUDE/LONGITUDE
602207,5588.0,020,029,TR 3733,NaN,157,17LA84605,16047-10001-00204,Swimming-Pool/Spa,1 or 2 Family Dwelling,...,DOLATIAN,NaN,556 RIVERDALE DR,NaN,"GLENDALE, CA",RE11-1,NaN,0.0,1892.02,"(34.1151, -118.29577)"
752187,5529.0,023,020,TR 3425,NaN,34,16VN10721,16047-20000-00022,Swimming-Pool/Spa,1 or 2 Family Dwelling,...,TARDINO,NaN,NaN,NaN,NaN,R1-1,Misc. Occ. Group,0.0,1944.01,"(34.0884, -118.36498)"
421894,5527.0,5.0,003,TR 4849,NaN,141,18VN76443,18047-20000-00674,Swimming-Pool/Spa,1 or 2 Family Dwelling,...,NaN,NaN,14530 HAMLIN ST,NaN,VAN NUYS CA,R2-1XL,Misc. Occ. Group,0.0,1920.02,"(34.0868, -118.35831)"
421891,5432.0,15.0,020,TR 8423,NaN,37,17WL83032,17047-30000-01458,Swimming-Pool/Spa,1 or 2 Family Dwelling,...,LEFEBVRE,NaN,PO BOX 1204,NaN,LA CANADA,R1-1VL,Misc. Occ. Group,0.0,1951.00,"(34.1054, -118.2698)"
752193,2234.0,011,031,TR 14014,NaN,33,19VN86984,19047-20000-00216,Swimming-Pool/Spa,1 or 2 Family Dwelling,...,GASCA,NaN,NaN,NaN,NaN,R1-1-RIO,NaN,0.0,1277.11,"(34.1877, -118.47295)"

In [12]:
df.sort_values('PERMIT_TYPE' , ascending=True).head()

,ASSESSOR_BOOK,ASSESSOR_PAGE,ASSESSOR_PARCEL,TRACT,BLOCK,LOT,REFERENCE_#_(OLD_PERMIT_#),PCIS_PERMIT_#,PERMIT_TYPE,PERMIT_SUB-TYPE,...,APPLICANT_LAST_NAME,APPLICANT_BUSINESS_NAME,APPLICANT_ADDRESS_1,APPLICANT_ADDRESS_2,APPLICANT_ADDRESS_3,ZONE,OCCUPANCY,FLOOR_AREA-L.A._BUILDING_CODE_DEFINITION,CENSUS_TRACT,LATITUDE/LONGITUDE
867819,4241.0,007,016,VENICE ANNEX NO. 2,1,16,16WL73541,14014-10000-05112,Bldg-Addition,1 or 2 Family Dwelling,...,KIM,NaN,972 S. LA FAYETTE PARK PL.,#42,CA,RD1.5-1,NaN,3004.0,2736.00,"(33.99485, -118.46293)"
626426,2014.0,4.0,019,TR 21396,NaN,87,18SL63969,18014-70000-02081,Bldg-Addition,1 or 2 Family Dwelling,...,CORTEZ,NaN,1168 SAN GABRIEL,NaN,ROSEMEAD,RS-1,NaN,707.0,1343.02,"(34.21785, -118.62591)"
40467,2639.0,034,004,TR 15442,NaN,14,20VN14567,20014-20000-00512,Bldg-Addition,1 or 2 Family Dwelling,...,NaN,NaN,185700 SHERMAN WAY,#210,RESEDA CA,R1-1,NaN,445.0,1199.00,"(34.2319, -118.44127)"
407457,2524.0,030,033,TR 13778,NaN,52,16VN29854,16014-20000-04882,Bldg-Addition,1 or 2 Family Dwelling,...,NaN,OWNER-BUILDER,6179 VAN NUYS B.,NaN,VAN NUYS CA,R1-1-CUGU,NaN,736.0,1043.20,"(34.27882, -118.41943)"
40476,4392.0,008,009,TR 6415,NaN,75,20WL05173,17014-10000-01216,Bldg-Addition,1 or 2 Family Dwelling,...,MCNAMARA,NaN,14726 RAMONA AVE,410-WI,"CHINO, CA",RE11-1,NaN,361.0,1943.00,"(34.0952, -118.39212)"

In [49]:
df['APPLICANT_ADDRESS_3'].to_list()

[nan,
 nan,
 nan,
 'Van Nuys',
 nan,
 'SANTA ANA, CA',
 nan,
 'VAN NUYS,CA',
 'Yucaipa',
 nan,
 '-',
 'LOS ANGELES CA',
 'VALLEY VILLAGE, CA',
 nan,
 'VAN NUYS, CA',
 nan,
 nan,
 nan,
 nan,
 nan,
 'Los Angeles',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'van nuys',
 'LOS ANGELES, CA',
 'HUNTINGTON BEACH, CA',
 nan,
 'WOODLAND HILLS, CA',
 nan,
 'LOS ANGELES, CA',
 nan,
 nan,
 nan,
 nan,
 nan,
 'LOS ANGELES, CA',
 'WEST HILLS, CA',
 nan,
 'CANOGA PARK, CA',
 nan,
 'SHERMAN OAKS, CA',
 'WOODLAND HILLS, CA',
 nan,
 nan,
 'CORONA, CA',
 'BURBANK, CA',
 nan,
 nan,
 'SUN VALLEY, CA',
 'TARZANA',
 nan,
 'VENICE, CA',
 'SANTA MONICA, CA',
 nan,
 nan,
 nan,
 nan,
 'SH OAKS, CA',
 nan,
 'SUNLAND, CA',
 'LOS ANGELES, CA',
 nan,
 nan,
 nan,
 'RESEDA, CA',
 nan,
 nan,
 nan,
 'CORONA, CA',
 'LANCASTER, CA',
 nan,
 nan,
 nan,
 nan,
 'ENCINO',
 'LOS ANGELES, CA',
 nan,
 nan,
 'TORRANCE, CA',
 nan,
 nan,
 'PANORAMA CITY, CA',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'WINNETKA, CA',
 'LOS ANGELES, CA',
 nan,
 'VAN NUYS, CA',
 nan,
 'VENICE, CA',
 'CERRITOS, CA',
 'WINNETKA, CA',
 nan,
 nan,
 nan,
 nan,
 nan,
 'LOS ANGELES, CA',
 'ARLETA, CA',
 nan,
 'ALHAMBRA, CA',
 nan,
 nan,
 nan,
 nan,
 'NORTH HILLS, CA',
 '.',
 nan,
 nan,
 nan,
 'RANCHO CUCAMONGA, CA',
 nan,
 nan,
 nan,
 'NORTH HOLLYWOOD, CA',
 'GLENDALE, CA',
 'MANHATTAN BEACH, CA',
 'LOS ANGELES, CA',
 nan,
 'BEVERLY HILLS, CA',
 nan,
 nan,
 'NEWBURY PARK, CA',
 nan,
 'Chatsworth',
 nan,
 'VALENCIA, CA',
 'LOS ANGELES, CA',
 nan,
 nan,
 'LOS ANGELES, CA',
 nan,
 nan,
 'LOS ANGELES, CA',
 nan,
 'ONTARIO, CA',
 nan,
 'NORCO, CA',
 nan,
 nan,
 'CANOGA PARK, CA',
 'Commerce',
 nan,
 nan,
 'TORRANCE, CA',
 nan,
 nan,
 nan,
 'Torrance',
 'LOS ANGELES, CA',
 nan,
 '.',
 'SANTAFESPRINGS, CA',
 'SYLMAR, CA',
 'CALABASAS, CA',
 'GLENDALE, CA',
 '.',
 nan,
 'BREA, CA',
 'WOODLAND HILLS, CA',
 nan,
 nan,
 'LOS ANGELES , CA',
 nan,
 nan,
 'NEWBURY PARK, CA',
 'Marina Del Rey',
 'MONTROSE,  CA, CA',
 nan,
 nan,
 'SHERMAN OAKS, CA',
 nan,
 'VAN NUYS CA',
 nan,
 '.',
 nan,
 nan,
 nan,
 'LAWNDALE, CA',
 'SANTA CLARITA, CA',
 'LA, CA',
 nan,
 'SIMIVALLEY, CA',
 nan,
 'NEWBURY PARK, CA',
 nan,
 nan,
 nan,
 'SANTA ANA, CA',
 'LOS ANGELES, CA',
 nan,
 nan,
 'BURBANK, CA',
 'Pasadena',
 'LOS ANGELES, CA',
 'NORTH HILLS,CA',
 'NEWBURY PARK, CA',
 'LOS ANGELES,CA',
 nan,
 nan,
 'VAN NUYS, CA',
 'STUDIO CITY, CA',
 nan,
 'V N',
 'TARZANA CA',
 nan,
 'TUJUNGA, CA',
 nan,
 nan,
 nan,
 'P.C.',
 'CANOGA PARK, CA',
 'CAMARILLO, CA',
 '1',
 'LOS ANGELES, CA',
 'Commerce',
 'ENCINO, CA',
 nan,
 'HUNTINGTON PARK, CA',
 nan,
 nan,
 'WEST HILLS,CA',
 nan,
 'SAN PEDRO, CA',
 nan,
 'LOS ANGELES, CA',
 nan,
 nan,
 'LOS ANGELES, CA',
 'ALHAMBRA, CA',
 'LONG BEACH, CA',
 nan,
 nan,
 'L.A., CA',
 'GLENDALE, CA',
 nan,
 'SUNLAND, CA',
 'SUN VALLEY, CA',
 nan,
 'TORRANCE, CA',
 'WOODLAND HILLS, CA',
 'RESEDA, CA',
 'LOS ANGELES, CA',
 'MORENO VALLEY, CA',
 'VAN NUYS, CA',
 'COMMERCE, CA',
 'BURBANK, CA',
 nan,
 'ORANGE, CA',
 '-',
 'LOS ANGELES, CA',
 'LOMITA, CA',
 '.',
 nan,
 'PASADENA, CA',
 'Bakersfield',
 nan,
 'LOS ANGELES, CA',
 nan,
 'LOS ANGELES,CA',
 'LOS ANGELES, CA',
 nan,
 nan,
 'CAMARILLO, CA',
 'ANAHEIM,CA',
 'LONG BEACH, CA',
 'TARZANA,CA',
 'GLENDALE, CA',
 'WOODLAND HILLS, CA',
 'SOUTHGATE, CA',
 'NORTH HOLLYWOOD, CA',
 'YUCAIPA, CA',
 'LOS ANGELES, CA',
 'IRVINE,CA',
 nan,
 'LOS ANGELES, CA',
 'CHATSWORTH, CA',
 nan,
 'PORTER RANCH',
 nan,
 'WOODLAND HILLS,CA',
 'BURBANK, CA',
 'BREA, CA',
 'Huntington beach',
 nan,
 nan,
 'LOS ANGELES, CA',
 'TARZANA, CA',
 'LOS ANGELES, CA',
 nan,
 nan,
 'LOS ANGELES, CA',
 nan,
 nan,
 'VALENCIA, CA',
 nan,
 'NORTH HILLS, CA',
 nan,
 'MONTEREY PARK, CA',
 'BURBANK, CA',
 nan,
 'TORRANCE, CA',
 'CHATSWORTH, CA',
 'chatsworth',
 nan,
 nan,
 'BURBANK, CA',
 '.',
 nan,
 'PORTER RANCH',
 nan,
 'CULVER CITY, CA',
 'NORTHRIDGE, CA',
 'SIMI VALLEY, CA',
 nan,
 nan,
 'VICTORVILLE, CA',
 'VAN NUYS, CA',
 nan,
 nan,
 nan,
 nan,
 nan,
 'NORWALK, CA',
 'LOS ANGELES',
 nan,
 'SUNLAND, CA',
 nan,
 'LOS ANGELES, CA',
 'NORTH HILLS CA',
 'chatsworth',
 '.',
 'WINNETKA, CA',
 'CHINO, CA',
 'BURBANK, CA',
 'LOMITA, CA',
 nan,
 nan,
 'Canoga Park',
 'LA, CA',
 'BURBANK',
 nan,
 'GLENDALE, CA',
 'Los Angeles',
 'LOS ANGELES, CA',
 nan,
 'CHATSWORTH, CA',
 nan,
 nan,
 nan,
 'BREA, CA',
 nan,
 'L A',
 nan,
 nan,
 '.',
 'WOODLAND HILLS, CA',
 'APPLE VALLEY, CA',
 'chatsworth',
 'PARAMOUNT, CA',
 nan,
 'SUN VALLEY, CA',
 nan,
 'LOS ANGELES, CA',
 'SHERMAN OAKS',
 'HERMOSA BEACH, CA',
 'RIVERSIDE, CA',
 'TORRACE, CA',
 nan,
 'NORTH HILLS, CA',
 'PLAYA VISTA, CA',
 nan,
 'ENCINO, CA',
 'LOS ANGELES, CA',
 nan,
 'LOS ANGELES, CA',
 nan,
 'TARZANA CA',
 nan,
 'VAN NUYS, CA',
 'ENCINO, CA',
 nan,
 'POMONA, CA',
 nan,
 nan,
 'MURRIETA, CA',
 nan,
 nan,
 'TARZANA, CA',
 'LOS ANGELES, CA',
 'PORTER RANCH, CA',
 'BLOOMINGTON, CA',
 nan,
 'CALABASAS, CA',
 nan,
 'WOODLAND HILLS, CA',
 nan,
 nan,
 'GLENDALE CA',
 'BAKERSFIELD,CA',
 nan,
 'SIMI VALLEY, CA',
 'SHERMAN OAKS, CA',
 nan,
 'ANAHEIM, CA',
 'BEVERLY HILLS, CA',
 nan,
 nan,
 'LANCASTER,CA',
 nan,
 'WEST HILLS, CA',
 nan,
 'NORTHRIDGE, CA',
 '.',
 'NORTHRIDGE, CA',
 'TARZANA, CA',
 'LAKEVIEW TERRACE, CA',
 nan,
 'SANTAFESPRINGS, CA',
 'WEST HILLS,CA',
 'LA CA',
 nan,
 'VAN NUYS, CA',
 'SYLMAR, CA',
 nan,
 'WOODLAND HILLS, CA',
 'CHATSWORTH, CA',
 nan,
 'TUJUNGA, CA',
 nan,
 'TARZANA CA',
 'ENCINO, CA',
 nan,
 'LOS ANGELES, CA',
 'VALLEY VILLAGE, CA',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'LA, CA',
 'LOS ANGELES, CA',
 nan,
 nan,
 nan,
 'N HOLLYWOOD, CA',
 'GARDENA, CA',
 nan,
 nan,
 'WEST HILLS,CA',
 nan,
 'HIGHLAND, CA',
 nan,
 'TARZANA, CA',
 'GRANADA HILLS, CA',
 'ENCINO, CA',
 nan,
 nan,
 nan,
 nan,
 nan,
 'LOS ANGELES CA',
 nan,
 'GARDENA, CA',
 nan,
 nan,
 '.',
 'Chatsworth',
 'WEST HILLS, CA',
 'LOS ANGELES, CA',
 'Downey',
 'LOS ANGELES, CA',
 'WINNETKA CA',
 nan,
 'NORTH HOLLYWOOD, CA',
 nan,
 'HACIENDA HEIGHTS, CA',
 nan,
 'Orange',
 'GLENDALE, CA',
 'SAN BERNARDINO, CA',
 'CANOGA PARK, CA',
 'LA, CA',
 nan,
 'SANTA FE SPRINGS, CA',
 nan,
 nan,
 nan,
 'BEVERLY HILLS, CA',
 '.',
 'LOS ANGELES, CA',
 'WEST HILLS, CA',
 'N. HOLLYWOOD, CA',
 nan,
 'LOS ANGELES, CA',
 nan,
 'BAKERSFIELD, CA',
 'SHERMAN OAKS, CA',
 nan,
 'LOS ANGELES, CA',
 'NORTH HOLLYWOOD, CA',
 'FRAZIER PARK, CA',
 nan,
 'LOS ANGELES, CA',
 'WOODLAND HILLS, CA',
 'LOS ANGELES, CA',
 'BREA, CA',
 nan,
 nan,
 'ARLETA, CA',
 nan,
 'LAKE HUGHES, CA',
 'WOODLAND HILLS, CA',
 'SANTA FE SPRINGS, CA',
 nan,
 'North Hollywood',
 'ENCINO, CA',
 'NEWHALL, CA',
 'MONTEBELLO, CA',
 'LOS ANGELES, CA',
 'SANTA MONICA, CA',
 nan,
 'BEVERLY HILLS, CA',
 'COMMERCE, CA',
 'LOS ANGELES, CA',
 'LANCASTER, CA',
 nan,
 nan,
 'WEST HILLS, CA',
 nan,
 nan,
 'SAN FERNANDO, CA',
 nan,
 nan,
 nan,
 'SUNLAND, CA',
 nan,
 nan,
 'SUN VALLEY, CA',
 'WOODLAND HILLS, CA',
 'ORANGE, CA',
 'SOUTH GATE, CA',
 'GRANADA HILLS, CA',
 'SHERMAN OAKS CA',
 nan,
 nan,
 'CALABASAS, CA',
 'LOS ANGELES, CA',
 'WINCHESTER,CA',
 nan,
 nan,
 'SANTA CLARITA, CA',
 nan,
 'chatsworth',
 'MANHATTAN BEACH, CA',
 'ANAHEIM, CA',
 nan,
 'SUN VALLEY, CA',
 'SANTA CLARITA, CA',
 'BAKERSFIELD, CA',
 nan,
 nan,
 'burbank',
 nan,
 'NORTH HOLLYWOOD, CA',
 'NORTHRIDGE, CA',
 nan,
 'LOS ANGELES, CA',
 'CA, CA',
 'NORTH HOLLYWOOD,CA',
 nan,
 nan,
 nan,
 'VAN NUYS, CA',
 'LOS ANGELES, CA',
 nan,
 nan,
 nan,
 'VAN NUYS, CA',
 nan,
 nan,
 'BREA, CA',
 'LOS ANGELES, CA',
 nan,
 nan,
 nan,
 'Commerce',
 nan,
 'SANTA MONICA',
 nan,
 'LOS ANGELES, CA',
 'BURBANK,CA',
 'COMMERCE, CA',
 nan,
 'GARDENA, CA',
 nan,
 nan,
 'QUARTZ HILL, CA',
 nan,
 nan,
 'ORANGE, CA',
 nan,
 nan,
 nan,
 nan,
 '.',
 'GLENDALE CA',
 'IRVINE, CA',
 nan,
 nan,
 nan,
 nan,
 'IRVINE',
 nan,
 'LOS ANGELES, CA',
 nan,
 nan,
 'LOS ANGELES, CA',
 'SANTA CLARITA, CA',
 '.',
 nan,
 'VALENCIA, CA',
 'LA MIRADA, CA',
 nan,
 'PARAMOUNT, CA',
 'LOS ANGELES, CA',
 nan,
 'LOS ANGELES, CA',
 nan,
 'CANOGA PARK, CA',
 'VAN NUYS, CA',
 nan,
 'NORTH HOLLYWOOD, CA',
 'SANTA MONICA, CA',
 'LOS ANGELES CA',
 'GRANADA HILLS, CA',
 nan,
 'PARAMOUNT, CA',
 'NORTH HOLLYWOOD, CA',
 nan,
 'CALABASAS, CA',
 'BREA, CA',
 'SH OAKS, CA',
 'PASADENA, CA',
 nan,
 '-',
 'GARDENA, CA',
 'CARSON, CA',
 'SIMI VALLEY, CA',
 nan,
 'PORTER RANCH CA',
 'WOODLAND HILLS, CA',
 'HAWTHORNE, CA',
 'CANOGA PARK, CA',
 'VAN NUYS, CA',
 'LOS ANGELES, CA',
 'HUNTINGTON BEACH, CALIFORNIA',
 'VALLEY VILLAGE, CA',
 nan,
 'SYLMAR, CA',
 'WOODLAND HILLS, CA',
 'PARAMOUNT, CA',
 nan,
 'BURBANK, CA',
 'YORBA LINDA, CA',
 'GARDENA, CA',
 'Van Nuys',
 'CANOGA PARK, CA',
 nan,
 'VAN NUYS, CA',
 nan,
 'PORTER RANCH, CA',
 'TUJUNGA, CA',
 nan,
 '.',
 'WOODLAND HILLS, CA',
 nan,
 'ANAHEIM, CA',
 nan,
 'LOS ANGELES, CA',
 'WOODLAND HILLS, CA',
 'BURBANK, CA',
 nan,
 'Tarzana',
 'LOS ANGELES, CA',
 'SHERMAN OAKS, CA',
 'BEVERLY HILLS, CA',
 'LA CRESCENTA, CA',
 'GLENDALE, CA',
 nan,
 'SAN CLEMENTE, CA',
 'FOUNTAIN VALLEY CA',
 'SYLMAR, CA',
 'ENCINO, CA',
 'N HOLLYWOOD, CA',
 'LOS ANGELES, CA',
 nan,
 'HACIENDA HEIGHTS, CA',
 'GLENDALE, CA',
 'VAN NUYS, CA',
 'VAN NUYS, CA',
 'NORTHRIDGE, CA',
 nan,
 nan,
 nan,
 'CULVER CITY, CA',
 nan,
 'ARLETA, CA',
 'LOS ANGELES, CA',
 'TARZANA, CA',
 'LOS ANGELES, CA',
 nan,
 nan,
 'VAN NUYS, CA',
 'LA, CA',
 'BEVERLY HILLS, CA',
 'SHERMAN OAKS CA',
 'LOS ANGLES, CA',
 'VALENCIA, CA',
 nan,
 'NORTH HOLLYWOOD CA',
 nan,
 nan,
 'NORTH HOLLYWOOD, CA',
 nan,
 nan,
 nan,
 'VALLEY VILLAGE, CA',
 '.',
 nan,
 nan,
 nan,
 'ORANGE, CA',
 'ANAHEIM, CA',
 nan,
 nan,
 'SANTA CLARITA, CA',
 'EL SEGUNDO, CA',
 'LOS ANGELES CA',
 'LOS ANGELES, CA',
 nan,
 nan,
 'GRASS VALLEY, CA',
 'ROSEMEAD, CA',
 nan,
 'SYLMAR, CA',
 'LANCASTER, CA',
 'LOS ANGELES, CA',
 'RANCHO DOMINGUEZ, CA',
 'CANYON COUNTRY, CA',
 'ANAHEIM, CA',
 'CALABASAS,CA',
 'EL MONTE, CA',
 'ARLETA, CA',
 'SANTA CLARITA, CA',
 'IRVINE, CA',
 nan,
 'BURBANK, CA',
 'Culver City',
 'RIVERSIDE, CA',
 nan,
 'LOS ANGELES, CA',
 'BAKERSFIELD, CA',
 nan,
 '.',
 'CANOGA PARK, CA',
 nan,
 'SANTA ANA, CA',
 nan,
 nan,
 nan,
 'NORTH HOLLYWOOD, CA',
 nan,
 'WOODLAND HILLS, CA',
 nan,
 nan,
 nan,
 'LOS ANGELES, CA',
 'SANTA ANA, CA',
 nan,
 'BEL AIR, CA',
 'PASADENA, CA',
 'LOS ANGELES, CA',
 nan,
 nan,
 'RIVERSIDE, CA',
 'LOS ANGELES, CA',
 'LOS ANGELES, CA',
 'SANTA CLARITA, CA',
 'IRVINE, CA',
 'SHERMAN OAKS, CA',
 'TORRANCE, CA',
 'WOODLAND HILLS CA',
 'WHITTIER CA',
 nan,
 'VAN NUYS, CA',
 nan,
 nan,
 nan,
 'CANOGA PARK, CA',
 'LOS ANGELES, CA',
 nan,
 'LOS ANGELES, CA',
 nan,
 'SAN FERNANDO, CA',
 'LA CA',
 nan,
 nan,
 'MISSION HILLS, CA',
 'BURBANK, CA',
 nan,
 nan,
 'GLENDALE, CA',
 nan,
 'GRANADA HILLS, CA',
 nan,
 'LOS ANGELES, CA',
 'SHERMAN VILLAGE, CA',
 'CANOGA PARK, CA',
 nan,
 'SANTA FE SPRINGS, CA',
 'RESEDA, CA',
 'SANTA MONICA, CA',
 nan,
 nan,
 'VAN NUYS, CA',
 'CANOGA PARK, CA',
 'ANAHEIM, CA',
 nan,
 'BRADBURY, CA',
 'BREA, CA',
 'N HOLLYWOOD,CA',
 'CAMARILLO CA',
 nan,
 'GLENDALE, CA',
 'SUN VALLEY, CA',
 'WEST HILLS, CA',
 'CANYON COUNTRY, CA',
 nan,
 'VAN NUYS, CA',
 'GLENDORA, CA',
 'TUSTIN, CA',
 nan,
 'LOS ANGELES CA',
 'GARDENA, CA',
 nan,
 nan,
 'BEVERLY HILLS CA',
 'LOS ANGELES, CA',
 'VAN NUYS CA',
 nan,
 nan,
 'GLENDALE, CA',
 'ANAHEIM, CA',
 'HAWTHORNE, CA',
 'INGLEWOOD, CA',
 '-',
 nan,
 nan,
 'TARZANA, CA',
 'PACOIMA, CA',
 'QUARTZ HILL, CA',
 nan,
 nan,
 nan,
 nan,
 nan,
 'PLAYA DEL REY, CA',
 'VAN NUYS,CA',
 'TARZANAMCA',
 'NORTH HOLLYWOOD, CA',
 nan,
 nan,
 'PORTER RANCH, CA',
 nan,
 nan,
 nan,
 nan,
 'GARDENA, CA',
 'RESEDA CA',
 nan,
 'BEVERLY HILLS, CA',
 'PALMDALE, CA',
 'SHERMAN OAKS, CA',
 'LOS ANGELES, CA',
 nan,
 nan,
 'LOS ANGELES, CA',
 nan,
 nan,
 'LOS ANGELES, CA',
 'NORTH HOLLYWOOD, CA',
 'IRVINE, CA',
 nan,
 'HAWTHORNE, CA',
 nan,
 'HAWTHORNE, CA',
 'PASADENA, CA',
 nan,
 nan,
 'BURBANK, CA',
 'SANTA MONICA, CA',
 'L.A., CA',
 nan,
 nan,
 nan,
 'PARAMOUNT, CA',
 'IRVINE, CA',
 nan,
 'LOS ANGELES, CA',
 nan,
 nan,
 nan,
 'LOS ANGELES, CA',
 nan,
 nan,
 'CAMARILLO, CA',
 'BUEANA PARK, CA',
 nan,
 '-',
 nan,
 'NORTH HOLLYWOOD, CA',
 '.',
 nan,
 'PHOENIX, AZ',
 nan,
 'BLUE JAY, CA',
 'GRANADA HILLS / CA.',
 'NORTH HOLLYWOOD, CA',
 nan,
 'LONG BEACH CA',
 nan,
 nan,
 nan,
 nan,
 'TARZANA, CA',
 'LOS ANGELES ,CA 90034',
 'LOS ANGELES, CA',
 'BREA, CA',
 'PORTER RANCH, CA',
 'SUN VALLEY, CA',
 'CANOGA PARK, CA',
 nan,
 'LOS ANGELES, CA',
 nan,
 'CYPRESS, CA',
 'ALHAMBRA, CA',
 'VALLEY GLEN, CA',
 nan,
 'TRABUCO CANYON, CA',
 nan,
 nan,
 'VAN NUYS,CA',
 nan,
 'CLAREMONT, CA',
 'RESEDA, CA',
 'WEST HILLS, CA',
 nan,
 'NORTH HOLLYWOOD, CA',
 'ARLETA, CA',
 nan,
 nan,
 nan,
 'ONTARIO, CA',
 'WOODLAND HILLS, CA',
 'MONTEREY PARK, CA',
 '.',
 'SAN PEDRO, CA',
 nan,
 nan,
 'PASADENA, CA',
 nan,
 'TARZANA, CA',
 'WOODLAND HILLS, CA',
 'VALLEY VILLAGE, CA',
 nan,
 'PORTER RANCH',
 'OXNARD, CA',
 'GARDENA, CA',
 nan,
 'LOS ANGELES, CA',
 nan,
 nan,
 'LOS ANGELES, CA',
 ...]

In [21]:
df.value_counts('PERMIT_TYPE')

PERMIT_TYPE
Electrical              347111
Bldg-Alter/Repair       278322
Plumbing                209081
HVAC                    107443
Fire Sprinkler           45189
Bldg-Addition            39484
Bldg-New                 28319
Grading                  22752
Nonbldg-New              18603
Swimming-Pool/Spa        16847
Bldg-Demolition          15519
Elevator                 14731
Sign                     13132
Nonbldg-Alter/Repair      5319
Pressure Vessel           2129
Nonbldg-Addition           191
Nonbldg-Demolition          65
Bldg-Relocation             13
dtype: int64

In [20]:
df.value_counts('APPLICANT_ADDRESS_3')

APPLICANT_ADDRESS_3
LOS ANGELES, CA        92060
VAN NUYS, CA           23813
CANOGA PARK, CA        18311
NORTH HOLLYWOOD, CA    17049
WOODLAND HILLS, CA     14207
                       ...
INGLEWWOD, CA              1
INGLEWOOS, CA              1
INGLEWOOD.CA               1
INGLEWOOD  CA              1
| BREA, CA                 1
Length: 7023, dtype: int64

In [45]:
brentwood_permits = df[df['APPLICANT_ADDRESS_3'].fillna("").str.contains('BRENTWOOD')]

In [46]:
brentwood_permits[brentwood_permits['PERMIT_TYPE'].str.contains('Pool')]

Empty DataFrame
Columns: [ASSESSOR_BOOK, ASSESSOR_PAGE, ASSESSOR_PARCEL, TRACT, BLOCK, LOT, REFERENCE_#_(OLD_PERMIT_#), PCIS_PERMIT_#, PERMIT_TYPE, PERMIT_SUB-TYPE, PERMIT_CATEGORY, PROJECT_NUMBER, EVENT_CODE, INITIATING_OFFICE, ISSUE_DATE, ADDRESS_START, ADDRESS_FRACTION_START, ADDRESS_END, ADDRESS_FRACTION_END, STREET_DIRECTION, STREET_NAME, STREET_SUFFIX, SUFFIX_DIRECTION, UNIT_RANGE_START, UNIT_RANGE_END, ZIP_CODE, WORK_DESCRIPTION, VALUATION, FLOOR_AREA-L.A._ZONING_CODE_DEFINITION, #_OF_RESIDENTIAL_DWELLING_UNITS, #_OF_STORIES, CONTRACTOR'S_BUSINESS_NAME, CONTRACTOR_ADDRESS, CONTRACTOR_CITY, CONTRACTOR_STATE, LICENSE_TYPE, LICENSE_#, PRINCIPAL_FIRST_NAME, PRINCIPAL_MIDDLE_NAME, PRINCIPAL_LAST_NAME, LICENSE_EXPIRATION_DATE, APPLICANT_FIRST_NAME, APPLICANT_LAST_NAME, APPLICANT_BUSINESS_NAME, APPLICANT_ADDRESS_1, APPLICANT_ADDRESS_2, APPLICANT_ADDRESS_3, ZONE, OCCUPANCY, FLOOR_AREA-L.A._BUILDING_CODE_DEFINITION, CENSUS_TRACT, LATITUDE/LONGITUDE]
Index: []

[0 rows x 52 columns]

In [17]:
df.groupby(['PERMIT_TYPE'],['APPLICANT_ADDRESS_3'])

TypeError: unhashable type: 'list'

In [18]:
df['PERMIT_SUB-TYPE' , 'APPLICANT_ADDRESS_3'].value_counts()

KeyError: ('PERMIT_SUB-TYPE', 'APPLICANT_ADDRESS_3')

In [19]:
df.sort_values['PERMIT_SUB-TYPE'].value_counts('APPLICANT_ADDRESS_3')

TypeError: 'method' object is not subscriptable