In [1]:
import pandas as pd
import numpy as np

In [10]:
requests2016 = pd.read_csv('../data/rawLA311/2016MyLA311ServiceRequestData.csv', low_memory=False)

In [11]:
requests2017 = pd.read_csv('../data/rawLA311/2017MyLA311ServiceRequestData.csv', low_memory=False)

In [12]:
requests2018 = pd.read_csv('../data/rawLA311/2018MyLA311ServiceRequestData.csv', low_memory=False)

In [13]:
requests2019 = pd.read_csv('../data/rawLA311/2019MyLA311ServiceRequestData.csv', low_memory=False)

In [14]:
requests2020 = pd.read_csv('../data/rawLA311/2020MyLA311ServiceRequestData.csv', low_memory=False)

In [15]:
requests2021 = pd.read_csv('../data/rawLA311/2021MyLA311ServiceRequestData.csv', low_memory=False)

In [16]:
requests2016.head(5)

,SRNumber,CreatedDate,UpdatedDate,ActionTaken,Owner,RequestType,Status,RequestSource,MobileOS,Anonymous,...,Location,TBMPage,TBMColumn,TBMRow,APC,CD,CDMember,NC,NCName,PolicePrecinct
0,1-88224881,01/01/2016 08:12:00 AM,01/07/2016 07:39:00 AM,SR Created,BOS,Illegal Dumping Pickup,Closed,Call,NaN,N,...,"(34.051491916, -118.366682002)",633.0,A,4.0,Central APC,10.0,Herb J. Wesson Jr.,60.0,P.I.C.O. NC,WILSHIRE
1,1-88224921,01/01/2016 08:15:00 AM,01/02/2016 07:19:00 AM,SR Created,BOS,Dead Animal Removal,Closed,Call,NaN,Y,...,"(34.0844988814, -118.260274626)",594.0,E,6.0,East Los Angeles APC,13.0,Mitch O'Farrell,44.0,GREATER ECHO PARK ELYSIAN NC,NORTHEAST
2,1-88225061,01/01/2016 08:26:00 AM,01/04/2016 02:39:00 PM,SR Created,BOS,Dead Animal Removal,Closed,Call,NaN,N,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1-88226921,01/01/2016 08:28:00 AM,01/04/2016 02:52:00 PM,SR Created,BOS,Bulky Items,Closed,Call,NaN,N,...,"(34.0675498757, -118.204061549)",635.0,B,1.0,East Los Angeles APC,1.0,Gilbert Cedillo,47.0,LINCOLN HEIGHTS NC,HOLLENBECK
4,1-88227021,01/01/2016 08:29:00 AM,01/04/2016 12:31:00 PM,SR Created,BOS,Metal/Household Appliances,Closed,Call,NaN,N,...,"(34.0675498757, -118.204061549)",635.0,B,1.0,East Los Angeles APC,1.0,Gilbert Cedillo,47.0,LINCOLN HEIGHTS NC,HOLLENBECK

In [18]:
df_csv = pd.read_csv('../data/rawLA311/combined.csv', low_memory=False).drop([2123993])

ParserError: Error tokenizing data. C error: Expected 33 fields in line 2123993, saw 34